version: '3.7'
services:

  crawler:
    image: crawler:0.1
    restart: always
    command: sh -c "python -m main.py"
    container_name: crawler
    volumes:
      - ./digi_crawler:/digi_crawler
    environment:
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE: digi
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: digi
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
